name: allegro-dapg
channels:
  - defaults
dependencies:
  - python=3.6
  - pytorch
  - cudatoolkit=9.2
  - absl-py
  - pyparsing
  - pip:
    - gym
    - termcolor
    - git+file:/home/ss14499/development/mj_envs
      # - git+file:/home/ss14499/development/mjrl
    - git+ssh://git@github.com/ssilwal/mj_allegro.git
    - git+ssh://git@github.com/ssilwal/mjrl.git
    - git+ssh://git@github.com/NYU-robot-learning/Allegro-Inverse-Kinematics.git 
    - imageio
    - imageio-ffmpeg
      #- git+git://github.com/facebookresearch/hydra@1.1_branch
    - hydra-core #1.1.1v
    - matplotlib
    - wandb
    - tqdm
    - tabulate
    - opencv-python
    - ikpy
    - IPython

