name: allegro-dapg
channels:
  - defaults
dependencies:
  - python=3.6
  - pytorch
  - cudatoolkit=9.2
  - absl-py
  - pyparsing
  - pip:
    - gym
    - termcolor
    - git+git://github.com:openai/mujoco-py.git
    - git+git://github.com/vikashplus/mj_envs.git
    - imageio
    - imageio-ffmpeg
    - git+git://github.com/facebookresearch/hydra@0.11_branch